#!/usr/bin/env node
/**
 * Generates tools/drawn_anims/market_coin.json — a coin spinning about its
 * vertical axis, one frame per step of the turn.
 *
 *   node tools/make_coin_spin.js [--frames N] [--grid N]
 *
 * Generated for the same reason the moon phases are: a spin is geometry. A
 * disc turned away from you is an ellipse whose width is the radius times
 * cos(angle), collapsing to a line edge-on — easy to compute and genuinely
 * hard to place by eye at 20 cells across, which is why Nova asked rather than
 * drew. The look is hers to change; only the shape is arithmetic.
 *
 * NOT a Mario coin. What Nintendo owns is the appearance of theirs — the
 * particular gold, the shading, the mark on the face. A disc that narrows as
 * it turns is how every spinning round object looks. The palette here is taken
 * from animations already in this catalogue rather than invented, so it sits
 * with the rest of them instead of looking imported.
 *
 * Intended for the corner slot on the stocks screen, animating while the
 * market is open and still when it is not, so it says something rather than
 * only decorating. It must NOT be listed in any rate group in splash.cpp, or
 * the splash would start picking it.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const arg = (k, def) => {
  const i = process.argv.indexOf(k);
  return i >= 0 ? Number(process.argv[i + 1]) : def;
};

const N = arg('--grid', 20);          // grid side
const FRAMES = arg('--frames', 8);    // steps through a full turn
const R = 8.2;                        // coin radius in cells
const CX = (N - 1) / 2;
const CY = (N - 1) / 2;
const SUB = 4;                        // supersampling, as in make_moon_phases.js

// Index 0 is transparent. These three are lifted from `expression wink`, which
// is already in the catalogue — so this is the same gold the creature's own
// animations use rather than a new one invented for it.
const PALETTE = ['transparent', '#FFD24D', '#FFE699', '#FFD98A'];
const [_, RIM, FACE, INNER] = [0, 1, 2, 3];

// Where the face gives way to the rim, as a fraction of the current half-width.
// A coin is not a flat disc: it has a raised rim, and without one a plain gold
// circle reads as a moon rather than as money.
const RIM_FRAC = 0.62;
// The inner panel, slightly darker than the face, so the middle reads as
// struck rather than blank. Left plain on purpose — whatever mark belongs
// there is a design decision, not a geometric one.
const INNER_FRAC = 0.34;

function frameFor(turn) {
  // Width follows |cos|: full-on at 0, an edge at a quarter turn.
  const w = Math.abs(Math.cos(turn * 2 * Math.PI));
  const halfW = Math.max(0.55, R * w);      // never fully vanish; an empty
                                            // frame reads as a dropped frame
  const grid = Array.from({ length: N }, () => Array(N).fill(0));

  for (let gy = 0; gy < N; gy++) {
    for (let gx = 0; gx < N; gx++) {
      let rim = 0, face = 0, inner = 0, n = 0;
      for (let sy = 0; sy < SUB; sy++) {
        for (let sx = 0; sx < SUB; sx++) {
          const x = (gx + (sx + 0.5) / SUB - 0.5 - CX) / halfW;
          const y = (gy + (sy + 0.5) / SUB - 0.5 - CY) / R;
          const d = Math.sqrt(x * x + y * y);
          if (d > 1) continue;
          n++;
          if (d > RIM_FRAC) rim++;
          else if (d > INNER_FRAC) face++;
          else inner++;
        }
      }
      const total = SUB * SUB;
      if (!n || n * 2 < total) continue;
      grid[gy][gx] = (rim >= face && rim >= inner) ? RIM
                   : (face >= inner) ? FACE : INNER;
    }
  }
  return grid;
}

const frames = Array.from({ length: FRAMES }, (_, i) => ({
  // Fast enough to read as a spin rather than a slideshow. The edge-on frames
  // are held the same as the rest: shortening them makes the coin look like it
  // stutters, because the eye reads the thin frame as the fastest part already.
  hold: 90,
  grid: frameFor(i / FRAMES),
}));

const doc = {
  name: 'market coin',
  category: 'Stocks',
  description:
    'Generated by tools/make_coin_spin.js — a coin turning about its vertical ' +
    'axis. Shape is arithmetic (width = radius * |cos|); the palette is the ' +
    'gold already used by `expression wink`. Intended for the corner slot on ' +
    'the stocks screen, running while the market is open. Deliberately absent ' +
    'from every rate group in splash.cpp so nothing plays it as a splash.',
  palette: PALETTE,
  frames,
};

const OUT = path.join(__dirname, 'drawn_anims', 'market_coin.json');
fs.writeFileSync(OUT, JSON.stringify(doc, null, 2) + '\n');
console.log(`wrote ${path.relative(process.cwd(), OUT)} — ${FRAMES} frames, ${N}x${N}`);

const CH = { 0: ' ', 1: '#', 2: 'o', 3: '.' };
for (let i = 0; i < frames.length; i++) {
  const cells = frames[i].grid.flat().filter(Boolean).length;
  console.log(`\n[${i}] turn ${(i / FRAMES * 360).toFixed(0)}°  (${cells} cells)`);
  for (const row of frames[i].grid) console.log('   ' + row.map(v => CH[v]).join(''));
}
